name: Deploy to Proxmox
#test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Setup SSH Config to use cloudflared as a proxy
          cat >> ~/.ssh/config <<EOF
          Host ${{ secrets.SERVER_IP }}
            ProxyCommand cloudflared access ssh --hostname %h
            User ${{ secrets.SERVER_USER }}
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          EOF

      - name: Run Deployment Script
        run: |
          ssh ${{ secrets.SERVER_IP }} "bash /var/www/qsite/deploy.sh"
